title = "Vathsal"
baseURL = "https://vathsal.github.io/myWebsite/"
languageCode = "en-us"
theme = "airspace"
publishDir = "docs"

[menu]

  [[menu.header]]
    weight = 2
    name = "Work"
    url = "/work"
  [[menu.header]]
    weight = 3
    name = "Resume"
    url = "/blog"
  [[menu.header]]
    weight = 4
    name = "Contact"
    url = "/contact"

  [[menu.footer]]
    weight = 1
    name = "About me"
    url = "#"
  [[menu.footer]]
    weight = 2
    name = "Contact me"
    url = "#"
  [[menu.footer]]
    weight = 3
    name = "Resume"
    url = "#"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  dateFormat = "6 January 2006"

  home = "Home"

  [params.slider]
    enable = true
    title = "Vathsal Veena Shashidhar"
    subtitle = "Graphics/VR/AR Enthusiast &nbsp;&bull;&nbsp; Prototyper &nbsp;&bull;&nbsp; Design Thinker"

  [params.wrapper]
    enable = true
    title = "About Me"
    italic = "Hi! Bringing together innovative technologies, open standards and creative processes, I am a developer who aspires to create interactive experiences which are engaging and intellectually stimulating. An individual driven by visual cues, whose thoughts gallop amidst a loud constant chatter, I imprint an image of the things I see, am enticed to write down everything I hear and obsess about what I need to do next and how I am going to get there."
    paragraph = "An ardent admirer of minimalistic design and creative detailing, I also like to explore the myriad ways through which one can impact life with design. My varying interests and pursuits have helped me stay curious and open-minded and I strive to be a designer by passion, developer by profession, an esthete by vocation and a conversationalist by character. At the heart of all of these lies a young man who appreciates life and its simplicity. The iconic Julia Childs once said “People who love to eat are always the best people” and I absolutely swear by it. Good food and soulful music is all it takes to make me a happy man!"

  [params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = true
    title = "I believe ..."
    content = "An ardent admirer of minimalistic design and creative detailing, I also like to explore the myriad ways through which one can impact life with design. My varying interests and pursuits have helped me stay curious and open-minded and I strive to be a designer by passion, developer by profession, an esthete by vocation and a conversationalist by character. At the heart of all of these lies a young man who appreciates life and its simplicity. The iconic Julia Childs once said “People who love to eat are always the best people” and I absolutely swear by it. Good food and soulful music is all it takes to make me a happy man!"
    [params.feature.button]
      caption = "View Works"
      url = "#"

  [params.call]
    enable = true
    title = "Technology Design Stratergy "
    paragraph = "I am constantly striving to explore the nexus between art & technology"

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Let's catch up "
      address = "San Jose, California, USA"
      email = "Email: picasiovs@gmail.com"
