title = "Vathsal"
baseURL = "https://vathsal.github.io/myWebsite/"
languageCode = "en-us"
theme = "airspace"
publishDir = "docs"

[menu]

  [[menu.header]]
    weight = 2
    name = "Works"
    url = "/works"
  [[menu.header]]
    weight = 3
    name = "About"
    url = "/about"

#  [[menu.footer]]
#    weight = 1
#    name = "Home"
#    url = "#"
#  [[menu.footer]]
#    weight = 2
#    name = "About me"
#    url = "/resume"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  dateFormat = "6 January 2006"

  # home = "Home" (removes home button from header)

# MAIN  PAGE
  [params.landing]
    enable = true
    title1 = "Hey, I'm"
    title2 = "Vathsal"
    subtitle = "Immersive-Technology Enthusiast &nbsp;&bull;&nbsp; Conversationalist &nbsp;&bull;&nbsp; Design Thinker"

  [params.wrapper]
    enable = true
    title = "Well,"
    paragraph1 = "I am developer by vocation, a designer by passion, and an aesthete by choice."
    paragraph2 = "I am currently consulting as a Unity Developer for an Augmented Reality Project at Building 8, Facebook. Prior to this I was working as a VR software developer at Yerba Buena VR (A 360 video optimization VR Startup)."
    paragraph3 = "I recently graduated from the University of Southern California with a masters in Computer Graphics. My coursework was primarily focused on applied signal processing, computer graphics, physics-based simulation and Virtual Reality."
    caption = "View Works"

  [params.call]
    enable = true
    title = "Technology • Design • Stratergy "
    paragraph = "I am constantly striving to explore the nexus between art & technology"



#WORK PAGE
  [params.section2]
    enable = true
    title = "Here's what I've done so far"

  [params.section3]
    enable = true
    title = "Here's what I usually don't tell anyone"

  [params.section4]
   enable = true
   title = "Here's my journey in stills"
   caption = "Check out more of my work here"


#ABOUT PAGE
  [params.contact.box]
    title = "Let's connect"
    address = "San Jose, California, USA"
    email = "picasiovs@gmail.com"
    linkedin = "www.linkedin.com/in/vathsalvs"
    instagram = "picasiovs"
