title = "Vathsal"
baseURL = "https://vathsal.github.io/myWebsite/"
languageCode = "en-us"
theme = "airspace"
publishDir = "docs"

[menu]

  [[menu.header]]
    weight = 2
    name = "Work"
    url = "/work"
  [[menu.header]]
    weight = 3
    name = "About Me"
    url = "/resume"

  [[menu.footer]]
    weight = 1
    name = "Home"
    url = "#"
  [[menu.footer]]
    weight = 2
    name = "About me"
    url = "/resume"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  dateFormat = "6 January 2006"

  home = "Home"

  [params.slider]
    enable = true
    title = "Hi, I am Vathsal"
    subtitle = "Immersive-Technology Enthusiast &nbsp;&bull;&nbsp; Conversationalist &nbsp;&bull;&nbsp; Design Thinker"

  [params.wrapper]
    enable = true
    title = "Hey there,"
    paragraph1 = "I am Vathsal Veena Shashidhar."
    paragraph2 = "I am developer by vocation, a designer by passion, and an aesthete by choice."
    paragraph3 = "I am currently consulting as a Unity Developer for an Augmented Reality Project at Building 8, Facebook. Prior to this I was working as a VR software developer at YBVR."
    paragraph4 = "I recently graduated from USC with a masters in Computer Graphics. My coursework was primarily focused on applied signal processing, computer graphics, physics-based simulation and VR."
    paragraph5 = "Add view works button here ! "
    caption = "View Works"

  [params.section3]
    enable = true
    title = "How I do"
    paragraph1 = "Hi,"
    paragraph2 = "This is my process to approacing problems. "
    paragraph3 = "I aspire to combine the two to create experiences that celebrate human expression."
    paragraph4 = "An individual driven by visual cues, whose thoughts gallop amidst a loud constant chatter, I imprint an image of the things I see, am enticed to write down everything I hear and obsess about what I need to do next and how I am going to get there."
    paragraph5 = "Being a developer by education, a designer by passion, and an aesthete by heart, I am constantly striving to explore the nexus between art & technology. If you share the same interests, we should definetly chat. "


  [params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = true
    title = "What I do"

  [params.feature.button]
    caption = "View Works"
    url = "/work"

  [params.call]
    enable = true
    title = "Technology • Design • Stratergy "
    paragraph = "I am constantly striving to explore the nexus between art & technology"

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."

  [params.contact.form]
    name = "Your name"
    email = "Your email"
    subject = "Your subject"
    message = "Your message"
    button = "Send message"

  [params.contact.box]
    title = "Let's connect"
    address = "San Jose, California, USA"
    email = "picasiovs@gmail.com"
    linkedin = "www.linkedin.com/in/vathsalvs"
    instagram = "picasiovs"
