title = "Vathsal"
baseURL = "https://vathsal.github.io/myWebsite/"
languageCode = "en-us"
theme = "airspace"
publishDir = "docs"

[menu]

  [[menu.header]]
    weight = 2
    name = "Works"
    url = "/works"
  [[menu.header]]
    weight = 3
    name = "About"
    url = "/about"

#  [[menu.footer]]
#    weight = 1
#    name = "Home"
#    url = "#"
#  [[menu.footer]]
#    weight = 2
#    name = "About me"
#    url = "/resume"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

  dateFormat = "6 January 2006"

  # home = "Home" (removes home button from header)

# MAIN  PAGE
  [params.landing]
    enable = true
    title1 = ""
    title2 = "Vathsal Veena Shashidhar"
    subtitle = "Creative Coder &nbsp;&bull;&nbsp; Conversationalist &nbsp;&bull;&nbsp; Design Thinker"

  [params.wrapper]
    enable = true
    title = "Hello,"
    paragraph1 = ""
    paragraph2 = ""
    paragraph3 = ""
    caption = "View Works"

  [params.call]
    enable = true
    title = "Design Technology Stratergy "
    paragraph = ""



#WORK PAGE
  [params.section2]
    enable = true
    title = "Here's what I've done so far"

  [params.section3]
    enable = true
    title = "Here's are my obsessions"

  [params.section4]
   enable = true
   title = "Here's my journey in stills"
   caption = "Check out more of my work here"


#ABOUT PAGE
  [params.contact.box]
    title = "Let's connect"
    address = "San Jose, California, USA"
    email = "picasiovs@gmail.com"
    linkedin = "www.linkedin.com/in/vathsalvs"
    instagram = "picasiovs"
